Part1
lzy-v/PFMCPP_Project2 pull request #1
Opened 2021-09-03 11:23 UTC by lzy-v

2021-09-05 23:53 UTC, matkatmusic requested changes
Your code needs to conform to the coding standard.
Your indentation in each function needs fixing
- [x] revise

2021-09-06 00:13 UTC, lzy-v commented
fixed indentation

2021-09-06 00:19 UTC, lzy-v commented
re-opened

2021-09-06 00:48 UTC, lzy-v commented
indented

2021-09-06 00:48 UTC, matkatmusic approved these changes

2021-09-06 00:48 UTC, merged